import { Language, Translations } from './types';

export const LANGUAGES: { code: Language; label: string; dir: 'ltr' | 'rtl' }[] = [
  { code: 'en', label: 'English', dir: 'ltr' },
  { code: 'zh', label: '简体中文', dir: 'ltr' },
  { code: 'ja', label: '日本語', dir: 'ltr' },
  { code: 'ar', label: 'العربية', dir: 'rtl' },
];

export const I18N: Record<Language, Translations> = {
  en: {
    title: 'Sunsetology',
    general: 'General Extractor',
    sunsetMode: 'Sunset Mode',
    subtitle: 'Turn your sunset moments into eternal art.',
    uploadText: 'Drop your photo here',
    uploadSubtext: 'Support JPG, PNG, WEBP. Privacy focused.',
    analyzing: 'Extracting colors...',
    palette: 'Chromatic DNA',
    gradient: 'Atmosphere',
    cardView: 'Share Card',
    download: 'Save Art',
    reset: 'New Capture',
    shareTitle: 'Color Palette',
    exampleImages: 'Example Images',
    useThisImage: 'Use this image',
    quotes: [
      "Sunsets are proof that no matter what happens, every day can end beautifully.",
      "The sky broke like an egg into full sunset and the water caught fire.",
      "Every sunset brings the promise of a new dawn.",
      "Softly the evening came with the sunset."
    ],
    original: 'Original',
    artisticWallpaper: 'Artistic Wallpaper',
    sunsetologyGradient: 'Sunsetology 180° Gradient',
    generated: 'Generated',
    bySunsetologyApp: 'By Sunsetology App',
    linear: 'Linear',
    radial: 'Radial',
    compare: 'Compare',
    wallpaper: 'Wallpaper',
    card: 'Card',
    comparisonView: 'Comparison View',
    portraitView: '9:16 Portrait',
    socialView: '4:5 Social',
    compareDimensions: '2160 x 1920px',
    wallpaperDimensions: '1080 x 1920px',
    cardDimensions: '1080 x 1350px',
    compareDescription: 'Side-by-side comparison of your original photo and artistic wallpaper. Perfect for sharing.',
    wallpaperDescription: 'Aesthetic gradient extracted from your photo. Perfect for lock screens.',
    cardDescription: 'Classic polaroid style with palette strip. Best for Instagram & Xiaohongshu.',
    saveImage: 'SAVE IMAGE',
    copied: 'COPIED',
    preview: 'PREVIEW',
    generateArt: 'Generate Art',
    generateMoreArt: 'Generate More Art',
    detectedDominantTones: 'Detected {count} dominant tones',
    primaryHexRgb: 'Primary HEX / RGB',
    primaryHslCmyk: 'Primary HSL / CMYK',
    footerQuote: 'The sky broke like an egg into full sunset and the water caught fire.',
    copyright: '© 2024 Sunsetology. Client-side processing only.',
    includeOriginal: 'Include Original',
    product: 'Product',
    atmosphere: 'Atmosphere',
    colorStory: 'Color Story',
    chromaticDna: 'Chromatic DNA'
  },
  zh: {
    title: '暮色工坊',
    general: '通用提取',
    sunsetMode: '日落模式',
    subtitle: '将日落瞬间凝固为永恒的色彩艺术。',
    uploadText: '拖入你的照片',
    uploadSubtext: '支持 JPG, PNG, WEBP。本地处理，隐私安全。',
    analyzing: '正在解析色彩...',
    palette: '色彩基因',
    gradient: '氛围渐变',
    cardView: '分享卡片',
    download: '保存创作',
    reset: '重新制作',
    shareTitle: '色彩色卡',
    exampleImages: '示例图片',
    useThisImage: '使用此图片',
    quotes: [
      "日落跌进昭昭星野，人间忽晚，山河已秋。",
      "落日余晖，待你而归。",
      "云朵偷喝了我放在屋顶的酒，于是它脸红变成了晚霞。",
      "晓看天色暮看云，行也思君，坐也思君。"
    ],
    original: '原图',
    artisticWallpaper: '艺术壁纸',
    sunsetologyGradient: '暮色工坊 180° 渐变',
    generated: '生成于',
    bySunsetologyApp: '由暮色工坊生成',
    linear: '线性',
    radial: '径向',
    compare: '对比',
    wallpaper: '壁纸',
    card: '卡片',
    comparisonView: '对比视图',
    portraitView: '9:16 竖屏',
    socialView: '4:5 社交',
    compareDimensions: '2160 x 1920px',
    wallpaperDimensions: '1080 x 1920px',
    cardDimensions: '1080 x 1350px',
    compareDescription: '原图与艺术壁纸的并排对比，非常适合分享。',
    wallpaperDescription: '从您的照片中提取的美学渐变，非常适合锁屏使用。',
    cardDescription: '经典宝丽来风格，配有调色板条，最适合 Instagram 和小红书。',
    saveImage: '保存图片',
    copied: '已复制',
    preview: '预览',
    generateArt: '生成艺术',
    generateMoreArt: '生成更多艺术',
    detectedDominantTones: '检测到 {count} 种主色调',
    primaryHexRgb: '主色调 HEX / RGB',
    primaryHslCmyk: '主色调 HSL / CMYK',
    footerQuote: '天空像被打破的蛋，化作了绚丽的日落，水面燃烧起来。',
    copyright: '© 2024 暮色工坊。仅在客户端处理。',
    includeOriginal: '包含原图',
    product: '产物',
    atmosphere: '氛围',
    colorStory: '色彩故事',
    chromaticDna: '色彩基因'
  },
  ja: {
    title: '夕暮れのアトリエ',
    general: '汎用抽出',
    sunsetMode: '夕焼けモード',
    subtitle: '夕日の瞬間を、永遠のアートカラーへ。',
    uploadText: 'ここに写真をドロップ',
    uploadSubtext: 'JPG, PNG, WEBP 対応。サーバーにはアップロードされません。',
    analyzing: '色彩を抽出中...',
    palette: '色彩パレット',
    gradient: 'グラデーション',
    cardView: 'シェアカード',
    download: '保存する',
    reset: '新規作成',
    shareTitle: '色彩パレット',
    exampleImages: 'サンプル画像',
    useThisImage: 'この画像を使用',
    quotes: [
      "夕焼けは、明日への希望の色。",
      "空が燃えるような、美しい別れ。",
      "一日が静かに幕を下ろす。",
      "黄昏時は、魔法の時間。"
    ],
    original: 'オリジナル',
    artisticWallpaper: 'アートウォールペーパー',
    sunsetologyGradient: '夕暮れアトリエ 180° グラデーション',
    generated: '生成',
    bySunsetologyApp: '夕暮れのアトリエによる',
    linear: 'リニア',
    radial: 'ラジアル',
    compare: '比較',
    wallpaper: 'ウォールペーパー',
    card: 'カード',
    comparisonView: '比較ビュー',
    portraitView: '9:16 ポートレート',
    socialView: '4:5 ソーシャル',
    compareDimensions: '2160 x 1920px',
    wallpaperDimensions: '1080 x 1920px',
    cardDimensions: '1080 x 1350px',
    compareDescription: '元の写真とアートウォールペーパーの比較。共有に最適。',
    wallpaperDescription: '写真から抽出した美的グラデーション。ロック画面に最適。',
    cardDescription: 'ポラロイドスタイルのカード。Instagramや小紅書に最適。',
    saveImage: '画像を保存',
    copied: 'コピー済み',
    preview: 'プレビュー',
    generateArt: 'アートを生成',
    generateMoreArt: 'より多くのアートを生成',
    detectedDominantTones: '{count} 色の主な色調を検出',
    primaryHexRgb: 'プライマリ HEX / RGB',
    primaryHslCmyk: 'プライマリ HSL / CMYK',
    footerQuote: '空が卵のように割れて、夕日が燃え上がり、水面が燃えた。',
    copyright: '© 2024 夕暮れのアトリエ。クライアント側でのみ処理されます。',
    includeOriginal: '元の画像を含める',
    product: 'プロダクト',
    atmosphere: 'アトモスフィア',
    colorStory: 'カラーストーリー',
    chromaticDna: 'クロマティックDNA'
  },
  ar: {
    title: 'ألوان الغروب',
    general: 'استخراج عام',
    sunsetMode: 'وضع الغروب',
    subtitle: 'حول لحظات الغروب إلى فنوني أبدية.',
    uploadText: 'أسقط صورة هنا',
    uploadSubtext: 'يدعم JPG, PNG, WEBP. خصوصية تامة.',
    analyzing: 'جارٍ استخراج الألوان...',
    palette: 'لوحة الألوان',
    gradient: 'تدرج لوني',
    cardView: 'بطاقة المشاركة',
    download: 'حفظ العمل',
    reset: 'صورة جديدة',
    shareTitle: 'لوحة الألوان',
    exampleImages: 'صور عينة',
    useThisImage: 'استخدم هذه الصورة',
    quotes: [
      "الغروب هو الدليل على أن النهايات يمكن أن تكون جميلة أيضًا.",
      "كل غروب يأتي بوعد لشروق جديد.",
      "تتحدث السماء بألوان عند الغروب.",
      "هدوء المساء يبدأ مع الغروب."
    ],
    original: 'الأصلية',
    artisticWallpaper: 'خلفية فنية',
    sunsetologyGradient: 'ألوان الغروب 180° التدرج',
    generated: 'تم إنشاؤه',
    bySunsetologyApp: 'بواسطة ألوان الغروب',
    linear: 'خطي',
    radial: 'شعاعي',
    compare: 'مقارنة',
    wallpaper: 'خلفية',
    card: 'بطاقة',
    comparisonView: 'عرض مقارنة',
    portraitView: 'تصوير عمودي 9:16',
    socialView: 'اجتماعي 4:5',
    compareDimensions: '2160 x 1920px',
    wallpaperDimensions: '1080 x 1920px',
    cardDimensions: '1080 x 1350px',
    compareDescription: 'مقارنة جنبًا إلى جنب للصورة الأصلية والخلفية الفنية. مثالي للمشاركة.',
    wallpaperDescription: 'تدرج لوني جمالي مستخرج من صورتك. مثالي للشاشة المغلقة.',
    cardDescription: 'أسلوب بولارويد كلاسيكي مع شريط لوحة الألوان. مثالي لإنستغرام والشاحنة الصغيرة الحمراء.',
    saveImage: 'حفظ الصورة',
    copied: 'تم النسخ',
    preview: 'معاينة',
    generateArt: 'توليد الفن',
    generateMoreArt: 'توليد المزيد من الفن',
    detectedDominantTones: 'تم اكتشاف {count} نغمة سائدة',
    primaryHexRgb: 'اللون الأساسي HEX / RGB',
    primaryHslCmyk: 'اللون الأساسي HSL / CMYK',
    footerQuote: 'انتشرت السماء كالبصل المكسور لتصبح غروبًا كاملًا واشتعلت الماء.',
    copyright: '© 2024 ألوان الغروب. معالجة فقط على الجانب العميل.',
    includeOriginal: 'تضمين الأصلية',
    product: 'المنتج',
    atmosphere: 'الجو',
    colorStory: 'قصة الألوان',
    chromaticDna: 'الدنا اللوني'
  }
};